export const ROUTES = {
  HOME: '/',
  MOVIES: '/movies',
  MOVIE_DETAIL: (id) => `/movies/${id}`,
  BOOKS: '/books',
  BOOK_DETAIL: (id) => `/books/${id}`,
  MANGA: '/manga',
  MANGA_DETAIL: (id) => `/manga/${id}`,
  COMICS: '/comics',
  COMIC_DETAIL: (id) => `/comics/${id}`,
  CART: '/cart',
  CHECKOUT: '/checkout',
  BECOME_SELLER: '/become-seller',
  WISHLIST: '/wishlist',
  PROFILE: '/profile',
  LOGIN: '/login',
  REGISTER: '/register',
  RESET_PASSWORD: '/reset-password',
  UPDATE_PASSWORD: '/update-password',
  DASHBOARD_ADMIN: '/dashboard/admin',
  DASHBOARD_ADMIN_PRODUCTS: '/dashboard/admin/products',
  DASHBOARD_ADMIN_ORDERS: '/dashboard/admin/orders',
  DASHBOARD_ADMIN_USERS: '/dashboard/admin/users',
  DASHBOARD_ADMIN_COUPONS: '/dashboard/admin/coupons',
  DASHBOARD_ADMIN_SELLERS: '/dashboard/admin/sellers',
  DASHBOARD_MANAGER: '/dashboard/manager',
  DASHBOARD_MANAGER_STAFF: '/dashboard/manager/staff',
  DASHBOARD_STAFF: '/dashboard/staff',
  DASHBOARD_STAFF_ORDERS: '/dashboard/staff/orders',
  DASHBOARD_SELLER: '/dashboard/seller',
  DASHBOARD_SELLER_PRODUCTS: '/dashboard/seller/products',
  DASHBOARD_SELLER_EARNINGS: '/dashboard/seller/earnings',
  DASHBOARD_SELLER_PAYOUTS: '/dashboard/seller/payouts',
  LOCAL_MOVIES: '/movies/local',
  LOCAL_MOVIE_DETAIL: (id) => `/movies/local/${id}`,
  ORDER_DETAIL: (id) => `/orders/${id}`,
  CONTACT: '/contact',
  FAQ: '/faq',
  PRIVACY: '/privacy',
  TERMS: '/terms',
}
