export const ROUTES = {
  HOME: '/',
  MOVIES: '/movies',
  MOVIE_DETAIL: (id) => `/movies/${id}`,
  BOOKS: '/books',
  BOOK_DETAIL: (id) => `/books/${id}`,
  MANGA: '/manga',
  MANGA_DETAIL: (id) => `/manga/${id}`,
  COMICS: '/comics',
  COMIC_DETAIL: (id) => `/comics/${id}`,
  PRODUCTS: '/products',
  PRODUCT_DETAIL: (id) => `/products/${id}`,
  CART: '/cart',
  CHECKOUT: '/checkout',
  WISHLIST: '/wishlist',
  PROFILE: '/profile',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD_ADMIN: '/dashboard/admin',
  DASHBOARD_ADMIN_PRODUCTS: '/dashboard/admin/products',
  DASHBOARD_ADMIN_ORDERS: '/dashboard/admin/orders',
  DASHBOARD_ADMIN_USERS: '/dashboard/admin/users',
  DASHBOARD_MANAGER: '/dashboard/manager',
  DASHBOARD_MANAGER_STAFF: '/dashboard/manager/staff',
  DASHBOARD_STAFF: '/dashboard/staff',
  DASHBOARD_STAFF_ORDERS: '/dashboard/staff/orders',
}
